global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "data-ingestion"
    static_configs:
      - targets: ["data-ingestion:50011"]
        labels:
          service: "data-ingestion"

  - job_name: "risk-engine"
    static_configs:
      - targets: ["risk-engine:50021"]
        labels:
          service: "risk-engine"

  - job_name: "strategy-engine"
    static_configs:
      - targets: ["strategy-engine:50031"]
        labels:
          service: "strategy-engine"

  - job_name: "execution-engine"
    static_configs:
      - targets: ["execution-engine:50041"]
        labels:
          service: "execution-engine"

  - job_name: "watchdog"
    static_configs:
      - targets: ["watchdog:50056"]
        labels:
          service: "watchdog"

  - job_name: "mock-exchange"
    static_configs:
      - targets: ["mock-exchange:50061"]
        labels:
          service: "mock-exchange"
